---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  loop:
    - "{{ ceph_rook_operator_configuration_directory }}"

- name: Render values file for rook-ceph operator helm chart
  ansible.builtin.template:
    src: operator.yml.j2
    dest: "{{ ceph_rook_operator_configuration_directory }}/operator.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
